// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wedding-invitation/Current.tsx": () => import("../components/mockups/wedding-invitation/Current.tsx"),
  "./components/mockups/wedding-invitation/variants/ArchitecturalGeometric.tsx": () => import("../components/mockups/wedding-invitation/variants/ArchitecturalGeometric.tsx"),
  "./components/mockups/wedding-invitation/variants/CulturalCelebration.tsx": () => import("../components/mockups/wedding-invitation/variants/CulturalCelebration.tsx"),
  "./components/mockups/wedding-invitation/variants/EditorialCeremony.tsx": () => import("../components/mockups/wedding-invitation/variants/EditorialCeremony.tsx"),
  "./components/mockups/wedding-invitation/variants/EditorialColumn.tsx": () => import("../components/mockups/wedding-invitation/variants/EditorialColumn.tsx"),
  "./components/mockups/wedding-invitation/variants/ModernNikah.tsx": () => import("../components/mockups/wedding-invitation/variants/ModernNikah.tsx"),
  "./components/mockups/wedding-invitation/variants/RoyalEmerald.tsx": () => import("../components/mockups/wedding-invitation/variants/RoyalEmerald.tsx")
};
